/**
 * Slug (URL segment) -> translation namespace id for tools.*.label
 */
export const SLUG_TO_ID = {
  "compress-image": "compressImage",
  "merge-pdf": "mergePdf",
  "heic-to-jpg": "heicToJpg",
  "resize-image": "resizeImage",
  "jpg-to-png": "jpgToPng",
  "pdf-to-jpg": "pdfToJpg",
  "png-to-jpg": "pngToJpg",
  "image-to-pdf": "imageToPdf",
  "compress-pdf": "compressPdf",
  "webp-to-jpg": "webpToJpg",
  "split-pdf": "splitPdf",
  "png-to-pdf": "pngToPdf",
  "jpg-to-pdf": "jpgToPdf",
  "svg-to-png": "svgToPng",
  "rotate-pdf": "rotatePdf",
  "image-to-webp": "imageToWebp",
  "pdf-to-png": "pdfToPng",
  "gif-to-mp4": "gifToMp4",
  "crop-image": "cropImage",
  "bmp-to-jpg": "bmpToJpg",
  "extract-pdf-pages": "extractPdfPages",
  "tiff-to-jpg": "tiffToJpg",
  "add-watermark-pdf": "addWatermarkPdf",
  "mp4-to-gif": "mp4ToGif",
  "jpg-to-webp": "jpgToWebp",
  "pdf-to-text": "pdfToText",
  "create-zip": "createZip",
  "trim-video": "trimVideo",
  "video-to-mp3": "videoToMp3",
  "compress-video": "compressVideo",
  "mute-video": "muteVideo",
  "video-speed": "videoSpeed",
  "add-audio-to-video": "addAudioToVideo",
  "resize-video": "resizeVideo",
  "merge-videos": "mergeVideos",
  "loop-video": "loopVideo",
};

/**
 * For each tool slug, list related tool slugs (similar or complementary).
 */
export const RELATED_TOOLS = {
  "compress-image": ["heic-to-jpg", "resize-image", "jpg-to-png"],
  "merge-pdf": ["compress-image", "pdf-to-jpg", "compress-pdf", "split-pdf"],
  "heic-to-jpg": ["compress-image", "jpg-to-png", "resize-image"],
  "resize-image": ["compress-image", "jpg-to-png", "heic-to-jpg", "crop-image"],
  "jpg-to-png": ["compress-image", "resize-image", "png-to-jpg"],
  "pdf-to-jpg": ["merge-pdf", "compress-image", "pdf-to-png"],
  "png-to-jpg": ["jpg-to-png", "webp-to-jpg", "compress-image", "resize-image"],
  "image-to-pdf": ["merge-pdf", "compress-pdf", "pdf-to-jpg", "png-to-pdf"],
  "compress-pdf": ["merge-pdf", "image-to-pdf", "pdf-to-jpg", "split-pdf"],
  "webp-to-jpg": ["png-to-jpg", "image-to-webp", "compress-image", "resize-image"],
  "split-pdf": ["merge-pdf", "compress-pdf", "extract-pdf-pages", "rotate-pdf"],
  "png-to-pdf": ["image-to-pdf", "jpg-to-pdf", "merge-pdf", "compress-pdf"],
  "jpg-to-pdf": ["image-to-pdf", "png-to-pdf", "merge-pdf", "compress-pdf"],
  "svg-to-png": ["jpg-to-png", "png-to-jpg", "compress-image", "resize-image"],
  "rotate-pdf": ["split-pdf", "merge-pdf", "compress-pdf", "pdf-to-jpg"],
  "image-to-webp": ["webp-to-jpg", "compress-image", "resize-image", "jpg-to-png"],
  "pdf-to-png": ["pdf-to-jpg", "merge-pdf", "split-pdf", "image-to-pdf"],
  "gif-to-mp4": ["compress-image", "image-to-webp", "resize-image"],
  "crop-image": ["resize-image", "compress-image", "jpg-to-png", "image-to-webp"],
  "bmp-to-jpg": ["webp-to-jpg", "png-to-jpg", "compress-image", "image-to-webp"],
  "extract-pdf-pages": ["split-pdf", "merge-pdf", "pdf-to-jpg", "compress-pdf"],
  "tiff-to-jpg": ["bmp-to-jpg", "png-to-jpg", "jpg-to-png", "compress-image"],
  "add-watermark-pdf": ["compress-pdf", "merge-pdf", "split-pdf", "rotate-pdf"],
  "mp4-to-gif": ["gif-to-mp4", "compress-image", "resize-image"],
  "jpg-to-webp": ["image-to-webp", "webp-to-jpg", "compress-image", "resize-image"],
  "pdf-to-text": ["pdf-to-jpg", "pdf-to-png", "split-pdf", "extract-pdf-pages"],
  "create-zip": ["extract-pdf-pages", "pdf-to-jpg", "image-to-pdf", "split-pdf"],
  "trim-video": ["compress-video", "video-to-mp3", "mute-video", "video-speed"],
  "video-to-mp3": ["trim-video", "compress-video", "add-audio-to-video", "mute-video"],
  "compress-video": ["trim-video", "video-to-mp3", "mute-video", "video-speed"],
  "mute-video": ["video-speed", "add-audio-to-video", "trim-video", "video-to-mp3"],
  "video-speed": ["mute-video", "trim-video", "compress-video", "add-audio-to-video"],
  "add-audio-to-video": ["mute-video", "video-to-mp3", "video-speed", "trim-video"],
  "resize-video": ["video-speed", "mute-video", "merge-videos", "loop-video"],
  "merge-videos": ["resize-video", "loop-video", "trim-video", "video-speed"],
  "loop-video": ["resize-video", "merge-videos", "video-speed", "mute-video"],
};
