/**
 * Slug (URL segment) -> translation namespace id for tools.*.label
 */
export const SLUG_TO_ID = {
  "compress-image": "compressImage",
  "merge-pdf": "mergePdf",
  "heic-to-jpg": "heicToJpg",
  "resize-image": "resizeImage",
  "jpg-to-png": "jpgToPng",
  "pdf-to-jpg": "pdfToJpg",
  "png-to-jpg": "pngToJpg",
  "image-to-pdf": "imageToPdf",
  "compress-pdf": "compressPdf",
  "webp-to-jpg": "webpToJpg",
  "split-pdf": "splitPdf",
  "png-to-pdf": "pngToPdf",
  "jpg-to-pdf": "jpgToPdf",
  "svg-to-png": "svgToPng",
  "rotate-pdf": "rotatePdf",
  "image-to-webp": "imageToWebp",
  "pdf-to-png": "pdfToPng",
  "gif-to-mp4": "gifToMp4",
  "crop-image": "cropImage",
  "bmp-to-jpg": "bmpToJpg",
  "extract-pdf-pages": "extractPdfPages",
  "tiff-to-jpg": "tiffToJpg",
  "add-watermark-pdf": "addWatermarkPdf",
  "mp4-to-gif": "mp4ToGif",
  "jpg-to-webp": "jpgToWebp",
  "pdf-to-text": "pdfToText",
  "create-zip": "createZip",
  "trim-video": "trimVideo",
  "video-to-mp3": "videoToMp3",
  "compress-video": "compressVideo",
  "mute-video": "muteVideo",
  "video-speed": "videoSpeed",
  "add-audio-to-video": "addAudioToVideo",
  "resize-video": "resizeVideo",
  "merge-videos": "mergeVideos",
  "loop-video": "loopVideo",
  "remove-background": "removeBackground",
  "resize-image-social": "resizeImageSocial",
  "add-text-to-image": "addTextToImage",
  "trim-audio": "trimAudio",
  "audio-to-mp3": "audioToMp3",
  "qr-code-generator": "qrCodeGenerator",
  "stl-viewer": "stlViewer",
  "obj-to-stl": "objToStl",
  "image-to-lithophane": "lithophane",
  "pdf-unlock": "pdfUnlock",
  "protect-pdf": "protectPdf",
  "pdf-add-page-numbers": "pdfPageNumbers",
  "reorder-pdf-pages": "reorderPdf",
  "word-to-pdf": "wordToPdf",
  "favicon-generator": "faviconGenerator",
  "dxf-viewer": "dxfViewer",
  "excel-to-pdf": "excelToPdf",
  "pdf-to-pdfa": "pdfToPdfa",
  "csv-to-pdf": "csvToPdf",
  "json-formatter": "jsonFormatter",
  "base64-encode-decode": "base64EncodeDecode",
  "image-to-text": "imageToText",
  "word-counter": "wordCounter",
  "text-case-converter": "textCaseConverter",
  "lorem-ipsum-generator": "loremIpsumGenerator",
  "add-watermark": "addWatermark",
  "color-converter": "colorConverter",
  "color-palette": "colorPalette",
  "csv-tools": "csvTools",
  "encrypt-text": "encryptText",
  "extract-audio": "extractAudio",
  "extract-frames": "extractFrames",
  "extract-zip": "extractZip",
  "markdown-to-pdf": "markdownToPdf",
  "markdown-to-html": "markdownToHtml",
  "merge-images": "mergeImages",
  "pdf-to-images": "pdfToImages",
  "pdf-to-pptx": "pdfToPptx",
  "pdf-to-word": "pdfToWord",
  "pdf-to-excel": "pdfToExcel",
  "powerpoint-to-pdf": "powerpointToPdf",
  "qr-generator": "qrGenerator",
  "remove-metadata": "removeMetadata",
  "text-diff": "textDiff",
  "compare": "compare",
  "dwg-to-pdf": "dwgToPdf",
  "dxf-to-pdf": "dxfToPdf",
  "unit-converter": "unitConverter",
  "password-generator": "passwordGenerator",
  "color-picker": "colorPicker",
  "url-encoder-decoder": "urlEncoderDecoder",
  "hash-generator": "hashGenerator",
  "age-calculator": "ageCalculator",
  "tip-calculator": "tipCalculator",
};

/**
 * For each tool slug, list related tool slugs (similar or complementary).
 */
export const RELATED_TOOLS = {
  "compress-image": ["heic-to-jpg", "resize-image", "jpg-to-png"],
  "merge-pdf": ["compress-image", "pdf-to-jpg", "compress-pdf", "split-pdf"],
  "heic-to-jpg": ["compress-image", "jpg-to-png", "resize-image"],
  "resize-image": ["compress-image", "jpg-to-png", "heic-to-jpg", "crop-image"],
  "jpg-to-png": ["compress-image", "resize-image", "png-to-jpg"],
  "pdf-to-jpg": ["merge-pdf", "compress-image", "pdf-to-png"],
  "png-to-jpg": ["jpg-to-png", "webp-to-jpg", "compress-image", "resize-image"],
  "image-to-pdf": ["merge-pdf", "compress-pdf", "pdf-to-jpg", "png-to-pdf"],
  "compress-pdf": ["merge-pdf", "image-to-pdf", "pdf-to-jpg", "split-pdf"],
  "webp-to-jpg": ["png-to-jpg", "image-to-webp", "compress-image", "resize-image"],
  "split-pdf": ["merge-pdf", "compress-pdf", "extract-pdf-pages", "rotate-pdf"],
  "png-to-pdf": ["image-to-pdf", "jpg-to-pdf", "merge-pdf", "compress-pdf"],
  "jpg-to-pdf": ["image-to-pdf", "png-to-pdf", "merge-pdf", "compress-pdf"],
  "svg-to-png": ["jpg-to-png", "png-to-jpg", "compress-image", "resize-image"],
  "rotate-pdf": ["split-pdf", "merge-pdf", "compress-pdf", "pdf-to-jpg"],
  "image-to-webp": ["webp-to-jpg", "compress-image", "resize-image", "jpg-to-png"],
  "pdf-to-png": ["pdf-to-jpg", "merge-pdf", "split-pdf", "image-to-pdf"],
  "gif-to-mp4": ["compress-image", "image-to-webp", "resize-image"],
  "crop-image": ["resize-image", "compress-image", "jpg-to-png", "image-to-webp"],
  "bmp-to-jpg": ["webp-to-jpg", "png-to-jpg", "compress-image", "image-to-webp"],
  "extract-pdf-pages": ["split-pdf", "merge-pdf", "pdf-to-jpg", "compress-pdf"],
  "tiff-to-jpg": ["bmp-to-jpg", "png-to-jpg", "jpg-to-png", "compress-image"],
  "add-watermark-pdf": ["compress-pdf", "merge-pdf", "split-pdf", "rotate-pdf"],
  "mp4-to-gif": ["gif-to-mp4", "compress-image", "resize-image"],
  "jpg-to-webp": ["image-to-webp", "webp-to-jpg", "compress-image", "resize-image"],
  "pdf-to-text": ["pdf-to-jpg", "pdf-to-png", "split-pdf", "extract-pdf-pages"],
  "create-zip": ["extract-pdf-pages", "pdf-to-jpg", "image-to-pdf", "split-pdf"],
  "trim-video": ["compress-video", "video-to-mp3", "mute-video", "video-speed"],
  "video-to-mp3": ["trim-video", "compress-video", "add-audio-to-video", "mute-video"],
  "compress-video": ["trim-video", "video-to-mp3", "mute-video", "video-speed"],
  "mute-video": ["video-speed", "add-audio-to-video", "trim-video", "video-to-mp3"],
  "video-speed": ["mute-video", "trim-video", "compress-video", "add-audio-to-video"],
  "add-audio-to-video": ["mute-video", "video-to-mp3", "video-speed", "trim-video"],
  "resize-video": ["video-speed", "mute-video", "merge-videos", "loop-video"],
  "merge-videos": ["resize-video", "loop-video", "trim-video", "video-speed"],
  "loop-video": ["resize-video", "merge-videos", "video-speed", "mute-video"],
  "remove-background": ["resize-image", "crop-image", "resize-image-social", "add-text-to-image"],
  "resize-image-social": ["resize-image", "remove-background", "add-text-to-image", "compress-image"],
  "add-text-to-image": ["remove-background", "resize-image-social", "crop-image", "compress-image"],
  "trim-audio": ["video-to-mp3", "audio-to-mp3", "mute-video", "add-audio-to-video"],
  "audio-to-mp3": ["video-to-mp3", "trim-audio", "add-audio-to-video", "mute-video"],
  "qr-code-generator": ["url-encoder-decoder", "password-generator", "hash-generator", "color-picker"],
  "stl-viewer": ["obj-to-stl", "image-to-lithophane"],
  "obj-to-stl": ["stl-viewer", "image-to-lithophane"],
  "image-to-lithophane": ["stl-viewer", "obj-to-stl"],
  "pdf-unlock": ["protect-pdf", "compress-pdf", "split-pdf", "pdf-to-text"],
  "protect-pdf": ["pdf-unlock", "compress-pdf", "add-watermark-pdf", "split-pdf"],
  "pdf-add-page-numbers": ["add-watermark-pdf", "rotate-pdf", "split-pdf", "merge-pdf"],
  "reorder-pdf-pages": ["split-pdf", "merge-pdf", "extract-pdf-pages", "rotate-pdf"],
  "word-to-pdf": ["image-to-pdf", "pdf-to-text", "merge-pdf", "compress-pdf"],
  "favicon-generator": ["create-zip", "resize-image", "compress-image", "qr-code-generator"],
  "dxf-viewer": ["stl-viewer", "obj-to-stl", "pdf-to-jpg", "image-to-pdf"],
  "excel-to-pdf": ["word-to-pdf", "csv-to-pdf", "image-to-pdf", "merge-pdf"],
  "pdf-to-pdfa": ["compress-pdf", "pdf-unlock", "protect-pdf", "add-watermark-pdf"],
  "csv-to-pdf": ["excel-to-pdf", "image-to-pdf", "pdf-to-text", "merge-pdf"],
  "json-formatter": ["word-counter", "text-case-converter", "url-encoder-decoder", "hash-generator", "color-picker", "base64-encode-decode"],
  "base64-encode-decode": ["word-counter", "text-case-converter", "json-formatter", "url-encoder-decoder", "hash-generator", "create-zip"],
  "image-to-text": ["pdf-to-text", "compress-image", "resize-image", "image-to-pdf"],
  "word-counter": ["text-case-converter", "lorem-ipsum-generator", "markdown-to-pdf", "json-formatter"],
  "text-case-converter": ["word-counter", "lorem-ipsum-generator", "json-formatter", "base64-encode-decode"],
  "lorem-ipsum-generator": ["word-counter", "text-case-converter", "markdown-to-pdf", "json-formatter"],
  "add-watermark": ["compress-image", "resize-image", "add-text-to-image", "remove-metadata"],
  "color-converter": ["color-palette", "compress-image", "resize-image", "remove-background"],
  "color-palette": ["color-converter", "compress-image", "remove-background", "add-text-to-image"],
  "csv-tools": ["csv-to-pdf", "excel-to-pdf", "json-formatter", "create-zip"],
  "encrypt-text": ["protect-pdf", "base64-encode-decode", "create-zip", "pdf-unlock"],
  "extract-audio": ["audio-to-mp3", "trim-audio", "video-to-mp3", "mute-video"],
  "extract-frames": ["gif-to-mp4", "mp4-to-gif", "compress-image", "resize-image"],
  "extract-zip": ["create-zip", "compress-image", "merge-pdf", "pdf-to-text"],
  "markdown-to-pdf": ["word-counter", "lorem-ipsum-generator", "pdf-to-text", "json-formatter"],
  "markdown-to-html": ["pdf-to-text", "word-to-pdf", "csv-to-pdf", "json-formatter"],
  "merge-images": ["compress-image", "resize-image", "image-to-pdf", "jpg-to-png"],
  "pdf-to-images": ["pdf-to-jpg", "pdf-to-png", "compress-pdf", "split-pdf"],
  "pdf-to-pptx": ["powerpoint-to-pdf", "pdf-to-word", "pdf-to-excel", "pdf-to-text"],
  "pdf-to-word": ["word-to-pdf", "pdf-to-text", "pdf-to-excel", "pdf-to-pptx"],
  "pdf-to-excel": ["excel-to-pdf", "pdf-to-text", "pdf-to-word", "csv-to-excel"],
  "powerpoint-to-pdf": ["pdf-to-pptx", "word-to-pdf", "excel-to-pdf", "merge-pdf"],
  "qr-generator": ["qr-code-generator", "favicon-generator", "create-zip", "compress-image"],
  "remove-metadata": ["compress-image", "resize-image", "add-watermark", "jpg-to-png"],
  "text-diff": ["json-formatter", "pdf-to-text", "encrypt-text", "markdown-to-html"],
  "compare": ["compress-image", "resize-image", "crop-image", "jpg-to-png"],
  "dwg-to-pdf": ["dxf-to-pdf", "dxf-viewer", "stl-viewer", "image-to-pdf"],
  "dxf-to-pdf": ["dwg-to-pdf", "dxf-viewer", "stl-viewer", "image-to-pdf"],
  "unit-converter": ["json-formatter", "word-counter", "text-case-converter", "lorem-ipsum-generator", "age-calculator", "tip-calculator"],
  "password-generator": ["base64-encode-decode", "hash-generator", "url-encoder-decoder", "protect-pdf", "create-zip", "json-formatter", "qr-code-generator"],
  "color-picker": ["favicon-generator", "image-to-text", "word-counter"],
  "url-encoder-decoder": ["base64-encode-decode", "json-formatter", "hash-generator"],
  "hash-generator": ["url-encoder-decoder", "base64-encode-decode", "password-generator", "json-formatter", "qr-code-generator"],
  "favicon-generator": ["create-zip", "resize-image", "compress-image", "qr-code-generator", "color-picker"],
  "age-calculator": ["unit-converter", "tip-calculator", "word-counter"],
  "tip-calculator": ["age-calculator", "unit-converter"],
};
