/**
 * Slug (URL segment) -> translation namespace id for tools.*.label
 */
export const SLUG_TO_ID = {
  "compress-image": "compressImage",
  "merge-pdf": "mergePdf",
  "compress-pdf": "compressPdf",
  "jpg-to-png": "jpgToPng",
  "png-to-jpg": "pngToJpg",
  "image-to-webp": "imageToWebp",
  "resize-image": "resizeImage",
  "pdf-to-images": "pdfToImages",
  "create-zip": "createZip",
  "extract-zip": "extractZip",
  "svg-to-png": "svgToPng",
  "remove-background": "removeBackground",
  "merge-images": "mergeImages",
  "pdf-to-text": "pdfToText",
  "add-watermark": "addWatermark",
  "color-converter": "colorConverter",
  "favicon-generator": "faviconGenerator",
  "compress-video": "compressVideo",
  "extract-audio": "extractAudio",
  "word-counter": "wordCounter",
  "heic-to-jpg": "heicToJpg",
  "remove-metadata": "removeMetadata",
  "pdf-to-pptx": "pdfToPptx",
  "color-palette": "colorPalette",
  "text-diff": "textDiff",
  "encrypt-text": "encryptText",
  "markdown-to-html": "markdownToHtml",
  "qr-generator": "qrGenerator",
  "extract-frames": "extractFrames",
  "csv-tools": "csvTools",
};

/**
 * For each tool slug, list 3-4 related tool slugs (similar or complementary).
 */
export const RELATED_TOOLS = {
  "compress-image": ["jpg-to-png", "resize-image", "image-to-webp", "remove-background"],
  "merge-pdf": ["compress-pdf", "pdf-to-images", "pdf-to-text", "create-zip"],
  "compress-pdf": ["merge-pdf", "pdf-to-images", "compress-image", "pdf-to-text"],
  "jpg-to-png": ["png-to-jpg", "heic-to-jpg", "image-to-webp", "compress-image"],
  "png-to-jpg": ["jpg-to-png", "image-to-webp", "compress-image", "favicon-generator"],
  "image-to-webp": ["compress-image", "resize-image", "jpg-to-png", "add-watermark"],
  "resize-image": ["compress-image", "image-to-webp", "jpg-to-png", "favicon-generator"],
  "pdf-to-images": ["merge-pdf", "pdf-to-pptx", "compress-pdf", "pdf-to-text"],
  "create-zip": ["extract-zip", "compress-pdf", "merge-pdf", "favicon-generator"],
  "extract-zip": ["create-zip", "compress-pdf", "merge-pdf"],
  "svg-to-png": ["jpg-to-png", "resize-image", "merge-images", "favicon-generator"],
  "remove-background": ["compress-image", "add-watermark", "merge-images", "png-to-jpg"],
  "merge-images": ["resize-image", "add-watermark", "svg-to-png", "compress-image"],
  "pdf-to-text": ["merge-pdf", "word-counter", "text-diff", "markdown-to-html"],
  "add-watermark": ["remove-background", "merge-images", "resize-image", "compress-image"],
  "color-converter": ["color-palette", "favicon-generator", "add-watermark"],
  "favicon-generator": ["svg-to-png", "resize-image", "png-to-jpg", "create-zip"],
  "compress-video": ["extract-audio", "merge-pdf", "create-zip"],
  "extract-audio": ["compress-video", "create-zip", "merge-pdf"],
  "word-counter": ["pdf-to-text", "merge-pdf", "create-zip", "text-diff"],
  "heic-to-jpg": ["jpg-to-png", "png-to-jpg", "compress-image", "image-to-webp"],
  "remove-metadata": ["compress-image", "jpg-to-png", "png-to-jpg", "add-watermark"],
  "pdf-to-pptx": ["pdf-to-images", "merge-pdf", "compress-pdf", "pdf-to-text"],
  "color-palette": ["color-converter", "add-watermark", "favicon-generator"],
  "text-diff": ["word-counter", "pdf-to-text", "encrypt-text", "markdown-to-html"],
  "encrypt-text": ["text-diff", "word-counter", "markdown-to-html"],
  "markdown-to-html": ["word-counter", "text-diff", "encrypt-text", "pdf-to-text"],
  "qr-generator": ["favicon-generator", "merge-images", "add-watermark"],
  "extract-frames": ["compress-video", "extract-audio", "pdf-to-images", "create-zip"],
  "csv-tools": ["create-zip", "extract-zip", "merge-pdf", "word-counter"],
};
