/**
 * FAQ (8–10 domande e risposte) per ogni tool. Usato per la sezione FAQ in pagina e per lo schema FAQPage.
 * Le chiavi corrispondono al path del tool (es. "compress-image").
 */
export const toolFaqs = {
  "compress-image": [
    {
      question: "How do you compress an image online?",
      answer:
        "Upload your photo (JPG, PNG or WebP) using the button, choose a quality level with the slider, then click compress. You can compare the original and compressed result side by side before downloading. Everything runs in your browser, so no data is sent to any server.",
    },
    {
      question: "Is image quality reduced?",
      answer:
        "Compression always involves a trade-off between file size and quality. You control this with the quality slider: lower values give smaller files but more visible loss. We recommend trying 60–80 for a good balance. The preview lets you check the result before downloading.",
    },
    {
      question: "What formats are supported?",
      answer:
        "You can upload and compress JPG (JPEG), PNG and WebP images. The compressed output keeps the same format as the original. These formats cover the vast majority of photos and graphics used on the web and in apps.",
    },
    {
      question: "Are files saved on the server?",
      answer:
        "No. All processing happens in your browser. Your images are never uploaded to our servers or stored anywhere. You stay in full control of your files from start to finish.",
    },
    {
      question: "Is there a file size limit?",
      answer:
        "There is no fixed limit set by the tool. Practical limits depend on your device and browser memory. Very large images (e.g. tens of megabytes) may take longer to process or, on low-memory devices, cause the browser to slow down. For typical photos (a few MB), there are no issues.",
    },
    {
      question: "What is the difference between JPG and PNG in compression?",
      answer:
        "JPG uses lossy compression: it discards some detail to achieve much smaller file sizes, which makes it ideal for photos. PNG uses lossless compression: it keeps every pixel intact but produces larger files, and is better for graphics with sharp edges or transparency. For photos on the web, JPG usually gives the best balance of size and quality; use PNG when you need transparency or exact reproduction of logos and UI elements.",
    },
    {
      question: "How do I compress images for WhatsApp?",
      answer:
        "WhatsApp automatically compresses photos when you send them, which can reduce quality. To keep control, compress your image first with this tool at a quality you choose (e.g. 75–80), then send the result: the file will be smaller and may be altered less by WhatsApp. Use JPG for photos; avoid sending huge originals so the app does not apply its own heavy compression. The tool runs in the browser, so you can do it quickly from your phone or computer before sharing.",
    },
    {
      question: "Can I compress multiple images at once?",
      answer:
        "Yes. You can add several images in one go: use the upload button and select multiple files, or drag and drop a batch. Each image is compressed separately and you can adjust quality per image if needed. When you are done, download each file individually or use the option to download all as a ZIP. Processing runs in your browser, so there is no limit imposed by the tool—only your device memory for very large batches.",
    },
    {
      question: "Is compression reversible?",
      answer:
        "No. Lossy compression (as used for JPG and WebP at lower quality) permanently removes some image data; you cannot restore the exact original from the compressed file. If you might need the full quality later, keep a copy of the original before compressing. PNG compression is lossless, so the image can be decoded back to the same pixels, but the file size reduction is smaller. This tool does not store your files, so always keep your originals on your device if you want to revert.",
    },
    {
      question: "What is the best format for photos on the web?",
      answer:
        "For most photos on websites and blogs, JPG is still the best choice: it gives small file sizes and good visual quality at 75–85% quality. WebP often produces even smaller files at similar quality and is supported by all modern browsers; use it when you want faster page loads. PNG is better for images with transparency or sharp graphics. Save photos as JPG or WebP for hero images, galleries, and thumbnails; use PNG for logos and graphics with transparent backgrounds.",
    },
  ],
  "merge-pdf": [
    {
      question: "How do I merge PDFs online?",
      answer:
        "Click the button to add one or more PDF files from your device. They appear in a list below. Drag the rows to change the order of the documents. When you are happy with the order, click “Merge PDF” to create a single PDF and download it. The process runs entirely in your browser, so your files never leave your device.",
    },
    {
      question: "Can I reorder the pages?",
      answer:
        "You reorder whole documents, not individual pages. Drag the file rows up or down to set the order in which each PDF appears in the merged file. The pages of each PDF keep their internal order; the merged PDF is document 1’s pages, then document 2’s, and so on. If you need to reorder single pages within a PDF, you would need a separate tool that supports page-level editing.",
    },
    {
      question: "Are my PDFs sent to a server?",
      answer:
        "No. Merging is done locally in your browser. Your files never leave your device or get stored on our servers. This keeps your documents private and secure. You can merge sensitive or confidential PDFs without any upload.",
    },
    {
      question: "Is there a limit to how many PDFs I can merge?",
      answer:
        "There is no fixed limit in the tool. Very large numbers of files or very big PDFs may make the browser use a lot of memory and take longer. For typical documents (e.g. a few dozen PDFs of a few MB each), merging works without issues. If you hit performance limits, try merging in smaller batches and then merging the resulting PDFs.",
    },
    {
      question: "Does merging reduce PDF quality?",
      answer:
        "No. The tool combines the existing content of your PDFs without re-encoding or re-compressing the pages. Text and images in the merged PDF stay at the same quality as in the originals. The output is a single PDF that behaves like one continuous document.",
    },
    {
      question: "Can I remove a file from the list before merging?",
      answer:
        "Yes. Each file in the list has a remove or delete option so you can take it out before clicking Merge. Reorder the remaining files as needed, then merge. If you change your mind, add the file again and adjust the order.",
    },
    {
      question: "What happens to bookmarks and links in the PDFs?",
      answer:
        "Bookmarks and internal links from the original PDFs are preserved in the merged file where the library supports it. Very complex PDFs with nested bookmarks may have simplified structure in the result. External links and hyperlinks generally remain clickable in the merged PDF.",
    },
    {
      question: "Does it work on mobile?",
      answer:
        "Yes. The tool runs in the mobile browser (Safari on iPhone, Chrome or others on Android). You can add PDFs from your device or cloud storage, reorder them, and download the merged file. No app install is required; processing happens in the browser so file size limits depend on your device’s memory.",
    },
    {
      question: "Can I merge password-protected PDFs?",
      answer:
        "Password-protected (encrypted) PDFs must be unlocked first before this tool can read them. Open the PDF with the correct password in another app, save it without password protection, then use that copy here. The merge tool itself does not ask for or handle PDF passwords.",
    },
  ],
  "heic-to-jpg": [
    {
      question: "What is HEIC?",
      answer:
        "HEIC (High Efficiency Image Container) is the default photo format on iPhones and some Android devices. It offers smaller file sizes than JPG at similar quality. Converting to JPG makes photos easier to share on social media, email, and websites that do not support HEIC, and the conversion runs in your browser so files never leave your device.",
    },
    {
      question: "Can I convert multiple files?",
      answer:
        "Yes. Select multiple HEIC files when you upload; the tool processes them one by one and shows progress. You can download each JPG individually or use the option to download all converted photos in a single ZIP. There is no fixed limit—very large batches may take longer depending on your device.",
    },
    {
      question: "Is quality lost?",
      answer:
        "JPG uses lossy compression, so there can be a small quality reduction compared to the original HEIC. For typical use (sharing, printing, web) the result is usually very good and the difference is hard to notice. If you need maximum quality, keep the HEIC originals for archival and use JPG for sharing.",
    },
    {
      question: "Are my photos sent to a server?",
      answer:
        "No. Conversion runs entirely in your browser. Your files never leave your device or get stored on our servers. This keeps your photos private and is ideal for personal or sensitive images.",
    },
    {
      question: "Why download as ZIP?",
      answer:
        "When you convert many files, downloading one ZIP is faster than saving each JPG individually. The ZIP contains all converted images with the same names (with .jpg extension). You can then extract them on your computer or phone and share or backup as needed.",
    },
    {
      question: "Does it work on iPhone and iPad?",
      answer:
        "Yes. Open the tool in Safari (or another browser) on your iPhone or iPad, then tap to add HEIC photos from your camera roll or Files app. The conversion runs in the browser and you can download each JPG or a ZIP. No app install is required.",
    },
    {
      question: "Are metadata and EXIF preserved?",
      answer:
        "Basic metadata such as date taken can be preserved when the conversion is done in the browser, depending on the library used. For full EXIF (camera model, GPS, etc.) preservation, some tools may strip or simplify it when encoding JPG. If you need exact EXIF, check the output or use a dedicated desktop tool.",
    },
    {
      question: "What is the output resolution?",
      answer:
        "The converted JPG keeps the same dimensions (pixel width and height) as the original HEIC. Only the format and compression change; resolution is not reduced. You get a standard JPG that you can use for print or web at the same size as the source.",
    },
    {
      question: "Can I convert HEIC to PNG or WebP instead?",
      answer:
        "This tool converts HEIC to JPG only. JPG is the most widely supported format for sharing and is sufficient for most uses. If you need PNG (e.g. for transparency) or WebP, you would need to convert HEIC to JPG first, then use another tool to convert JPG to the desired format, or use a converter that supports HEIC to PNG/WebP directly.",
    },
    {
      question: "How do I open a HEIC file on Windows/PC?",
      answer:
        "Windows does not open HEIC files natively; you may see a message that an app is needed. Converting HEIC to JPG with this tool solves the problem: upload the HEIC here, download the JPG, and open it in any Windows app. No extra software is required on your PC.",
    },
    {
      question: "What is the difference between HEIC and JPG?",
      answer:
        "HEIC typically produces smaller file sizes than JPG at similar visual quality, which is why iPhones use it. JPG is much more widely supported: it opens everywhere (Windows, websites, email, social media), while HEIC often requires conversion or specific apps. JPG uses lossy compression, so converting from HEIC to JPG can slightly reduce quality, but for most uses the result is excellent. In short: HEIC means smaller files and better compatibility with Apple devices; JPG means universal compatibility and slightly larger files.",
    },
    {
      question: "Can I convert a JPG back to HEIC?",
      answer:
        "Converting JPG back to HEIC is possible with some tools but usually not useful: JPG is lossy, so you would be saving already compressed data into HEIC without regaining the original quality or file size. For iPhone users, the best approach is to keep HEIC originals on the device or in iCloud and convert to JPG only when you need to share or use the photo elsewhere. This tool is for HEIC to JPG only; to keep new iPhone photos in HEIC, leave the camera format set to HEIC in Settings.",
    },
  ],
  "resize-image": [
    { question: "How do I resize an image online?", answer: "Upload your image (JPG, PNG, WebP), enter the desired width or height (or both), then click resize. The tool uses the browser canvas to resize. Download the result. Everything runs locally; no data is sent to any server." },
    { question: "Does resizing reduce quality?", answer: "Resizing to a smaller size reduces pixel count, so fine detail can be lost. Resizing to a larger size stretches pixels and can look soft. For best results, resize down when you need a smaller image; avoid enlarging small images too much." },
    { question: "Can I keep aspect ratio?", answer: "Yes. If you only enter width or only height, the other dimension is calculated automatically to preserve the original aspect ratio. You can also enter both to force specific dimensions (image may be stretched)." },
    { question: "What formats are supported?", answer: "You can upload JPG, PNG, and WebP. The output format matches the input. These are the most common image formats for web and photos." },
    { question: "Are my images uploaded to a server?", answer: "No. All processing happens in your browser using the canvas API. Your image never leaves your device." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very large images may take longer or use more memory. Typical photos (a few MB) work without issues." },
    { question: "Why would I resize an image?", answer: "Common reasons: fit a photo to a website or form size limit, create thumbnails, reduce dimensions for email, or match requirements for CVs, social media, or print." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Upload from your gallery, set dimensions, and download. No app install required." },
    { question: "Can I resize multiple images?", answer: "This tool processes one image at a time. For multiple images, use it repeatedly or combine with other tools." },
    { question: "What is the maximum output size?", answer: "Practical limits depend on your device and browser. Canvas has limits (often 16384px per side). For typical use (e.g. under 4000px), there are no issues." },
  ],
  "jpg-to-png": [
    { question: "How do I convert JPG to PNG online?", answer: "Upload your JPG file, then click convert. The tool uses the browser canvas to decode the JPG and encode a PNG. Download the result. Everything runs in your browser; no data is sent to any server." },
    { question: "Why convert JPG to PNG?", answer: "PNG supports transparency and is lossless, so it is better for logos, graphics with sharp edges, or when you need to edit without losing quality. JPG is better for photos due to smaller file size." },
    { question: "Will the file size increase?", answer: "Usually yes. PNG is lossless and often produces larger files than JPG for photos. For graphics with flat colors or transparency, PNG can be efficient." },
    { question: "Are my images sent to a server?", answer: "No. Conversion runs entirely in your browser using the canvas API. Your file never leaves your device." },
    { question: "What about transparency?", answer: "JPG does not support transparency. When you convert JPG to PNG, the output has no transparency (opaque background). For transparent PNGs, start from an image that already has transparency." },
    { question: "Does it work on mobile?", answer: "Yes. Open the tool in your mobile browser, upload a JPG, convert, and download the PNG. No app install required." },
    { question: "Can I convert PNG to JPG?", answer: "This tool is for JPG to PNG only. Use a compress or convert image tool for PNG to JPG." },
    { question: "Is quality lost?", answer: "No. PNG is lossless. The pixel data is preserved. File size may be larger than the original JPG." },
    { question: "What is the maximum image size?", answer: "Limits depend on your device and browser memory. Typical photos (several MB) work without issues." },
    { question: "Can I convert multiple JPGs?", answer: "This tool converts one file at a time. For batch conversion, use the tool repeatedly." },
  ],
  "pdf-to-jpg": [
    { question: "How do I convert PDF to JPG online?", answer: "Upload your PDF file. The tool renders each page to an image in the browser using PDF.js and the canvas, then encodes each as JPG. You can download each page as a separate JPG or all as a ZIP. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my PDFs sent to a server?", answer: "No. The PDF is loaded and rendered entirely in your browser. Your file never leaves your device." },
    { question: "What resolution are the JPGs?", answer: "The tool renders each page at a standard scale (e.g. 2x for clarity). You get a JPG per page suitable for web, email, or thumbnails. For very high resolution you may need a desktop app." },
    { question: "Can I choose which pages to convert?", answer: "This tool converts all pages. Each page becomes one JPG. You can delete unwanted JPGs after download or use a PDF tool to extract specific pages first." },
    { question: "Does it work with password-protected PDFs?", answer: "Password-protected PDFs must be unlocked first. Open the PDF with the correct password in another app, save without password, then use that copy here." },
    { question: "Why convert PDF to JPG?", answer: "JPGs are easier to insert in documents, websites, or emails. Converting to JPG is useful for sharing single pages, creating image galleries, or when the recipient cannot open PDFs." },
    { question: "Is text still selectable?", answer: "No. The output is an image (JPG). Text is not selectable or searchable. For editable text, use a PDF-to-text tool." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Large PDFs may take longer on mobile due to memory." },
    { question: "What about multi-page PDFs?", answer: "Each page is converted to a separate JPG. You get multiple files or one ZIP containing all pages in order." },
    { question: "Is there a page limit?", answer: "There is no fixed limit. Very long PDFs may take longer and use more memory. For typical documents (e.g. under 50 pages), conversion works well." },
  ],
  "png-to-jpg": [
    { question: "How do I convert PNG to JPG online?", answer: "Upload your PNG file, then click convert. The tool uses the browser canvas to decode the PNG and encode a JPG. Download the result. Everything runs in your browser; no data is sent to any server." },
    { question: "Why convert PNG to JPG?", answer: "JPG usually produces smaller file sizes than PNG for photos and is widely supported. Converting PNG to JPG is useful when you need a smaller file for web, email, or when the recipient expects JPG. Note: JPG does not support transparency; transparent areas become a solid background." },
    { question: "Will the file size decrease?", answer: "Often yes, especially for photos or complex images. PNG is lossless and can be larger. JPG uses lossy compression, so the file is typically smaller. For simple graphics with flat colors, the difference may be small." },
    { question: "Are my images sent to a server?", answer: "No. Conversion runs entirely in your browser using the canvas API. Your file never leaves your device." },
    { question: "What about transparency?", answer: "PNG can have transparency; JPG cannot. When you convert PNG to JPG, transparent areas are replaced with a solid background (usually white). If you need to keep transparency, stay with PNG or use another format that supports it." },
    { question: "Does it work on mobile?", answer: "Yes. Open the tool in your mobile browser, upload a PNG, convert, and download the JPG. No app install required." },
    { question: "Can I convert JPG to PNG?", answer: "This tool is for PNG to JPG only. Use the JPG to PNG tool for the reverse conversion." },
    { question: "Is quality lost?", answer: "Yes. JPG uses lossy compression, so some detail can be lost. For most photos the result is very good. You can often choose a quality level; higher quality means less loss but a larger file." },
    { question: "What is the maximum image size?", answer: "Limits depend on your device and browser memory. Typical images (several MB) work without issues." },
    { question: "Can I convert multiple PNGs?", answer: "This tool converts one file at a time. For batch conversion, use the tool repeatedly." },
  ],
  "image-to-pdf": [
    { question: "How do I convert images to PDF online?", answer: "Upload one or more images (JPG or PNG). They appear in a list. Optionally reorder them, then click the button to create a PDF. Each image becomes one page. Download the PDF. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my images sent to a server?", answer: "No. The tool uses pdf-lib in your browser to build the PDF. Your images never leave your device." },
    { question: "What image formats are supported?", answer: "JPG (JPEG) and PNG. These are the most common image formats. Each image is embedded as one page in the PDF." },
    { question: "Can I reorder the pages?", answer: "Yes. After uploading, you can drag the image rows to change the order. The PDF will be generated with pages in that order." },
    { question: "What size will the PDF be?", answer: "The PDF size depends on the size and number of images. Each image is embedded in the PDF, so the file can be large if you use many high-resolution images." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Upload images from your gallery, optionally reorder, and download the PDF. No app install required." },
    { question: "Can I add more images after uploading?", answer: "Yes. Use the upload button again to add more images. They are appended to the list. You can clear the list and start over if needed." },
    { question: "Is the PDF searchable?", answer: "No. The PDF contains images of your pictures. Text in the images is not selectable or searchable. For searchable PDFs you would need OCR or a tool that adds text layers." },
    { question: "Why convert images to PDF?", answer: "A single PDF is easier to share than many image files. PDFs are standard for documents, forms, and submissions. Converting images to PDF is useful for reports, portfolios, or when a system only accepts PDF." },
    { question: "Is there a page limit?", answer: "There is no fixed limit. Very many or very large images may use a lot of memory and take longer. For typical use (e.g. under 50 images), the tool works well." },
  ],
  "compress-pdf": [
    { question: "How do I compress a PDF online?", answer: "Upload your PDF file. Choose a compression level if the tool offers one, then click compress. The tool repackages the PDF in your browser using pdf-lib. Download the result. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my PDFs sent to a server?", answer: "No. Compression is done in your browser. Your PDF never leaves your device." },
    { question: "How much smaller will the file get?", answer: "It depends on the original PDF. Repackaging can remove redundant data and sometimes reduce size. PDFs that are already well compressed may not shrink much. For large reductions you might need a tool that re-encodes images inside the PDF." },
    { question: "Is quality lost?", answer: "This tool repackages the PDF without re-encoding images or text. The content stays the same. If you use a lower \"quality\" or \"compression\" setting in a tool that re-encodes images, then some image quality can be lost." },
    { question: "Does it work with password-protected PDFs?", answer: "Password-protected PDFs must be unlocked first. Open the PDF with the correct password in another app, save without password, then use that copy here." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Upload your PDF, compress, and download. No app install required." },
    { question: "Can I compress multiple PDFs?", answer: "This tool compresses one PDF at a time. For multiple files, use it repeatedly or merge them first with the merge PDF tool and then compress the merged file." },
    { question: "What is the difference between compress and merge?", answer: "Compress takes one PDF and tries to reduce its file size. Merge takes two or more PDFs and combines them into a single PDF. You can use both: merge first, then compress the result." },
    { question: "Why did my PDF get bigger?", answer: "Sometimes repackaging can slightly increase size if the original was very tightly packed. If the tool re-embeds fonts or images in a different way, the result can be larger. Try a different compression level if available." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very large PDFs may take longer and use more memory. For typical documents (e.g. under 100 MB), the tool works well." },
  ],
  "webp-to-jpg": [
    { question: "How do I convert WebP to JPG online?", answer: "Upload your WebP file, choose a quality level if shown, then click convert. The tool uses the browser canvas to decode the WebP and encode a JPG. Download the result. Everything runs in your browser; no data is sent to any server." },
    { question: "Why convert WebP to JPG?", answer: "WebP is efficient but not all apps or websites support it. JPG is universally supported. Converting to JPG is useful for sharing, printing, or when the recipient or system expects JPG." },
    { question: "Will the file size change?", answer: "Often JPG is larger than WebP at similar quality, but it depends on the image. You can choose a quality level: lower values mean smaller files but more compression. For maximum compatibility, JPG is the safe choice." },
    { question: "Are my images sent to a server?", answer: "No. Conversion runs entirely in your browser using the canvas API. Your file never leaves your device." },
    { question: "What about transparency?", answer: "WebP can have transparency; JPG cannot. When you convert WebP to JPG, transparent areas are replaced with a solid background (usually white). If you need transparency, keep the WebP or use PNG." },
    { question: "Does it work on mobile?", answer: "Yes. Open the tool in your mobile browser, upload a WebP, convert, and download the JPG. No app install required." },
    { question: "Can I convert JPG to WebP?", answer: "This tool is for WebP to JPG only. Use the image to WebP or compress image tool for the reverse or other conversions." },
    { question: "Is quality lost?", answer: "JPG uses lossy compression, so some detail can be lost. For most photos the result is very good. You can choose a quality level; higher quality means less loss but a larger file." },
    { question: "What is the maximum image size?", answer: "Limits depend on your device and browser memory. Typical images (several MB) work without issues." },
    { question: "Can I convert multiple WebP files?", answer: "This tool converts one file at a time. For batch conversion, use the tool repeatedly." },
  ],
  "split-pdf": [
    { question: "How do I split a PDF online?", answer: "Upload your PDF file. The tool loads it in your browser and splits it so each page becomes a separate PDF. Click the button to split, then download all pages as a single ZIP file. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my PDFs sent to a server?", answer: "No. Splitting is done in your browser using pdf-lib. Your PDF never leaves your device." },
    { question: "Can I choose which pages to split?", answer: "This tool splits every page into its own PDF. You get one PDF per page, all bundled in a ZIP. If you need only certain pages, extract them from the ZIP after download or use a PDF editor to remove unwanted pages first." },
    { question: "What are the output file names?", answer: "Each page is saved as a separate PDF in the ZIP, typically named by page number (e.g. page-1.pdf, page-2.pdf). You can rename them after extracting the ZIP." },
    { question: "Does it work with password-protected PDFs?", answer: "Password-protected PDFs must be unlocked first. Open the PDF with the correct password in another app, save without password, then use that copy here." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Upload your PDF, split, and download the ZIP. No app install required." },
    { question: "Is there a page limit?", answer: "There is no fixed limit. Very long PDFs may take longer and use more memory. For typical documents (e.g. under 100 pages), splitting works well." },
    { question: "What is the difference between split and merge?", answer: "Split takes one PDF and creates separate PDFs (one per page), then packs them in a ZIP. Merge takes two or more PDFs and combines them into a single PDF. They are opposite operations." },
    { question: "Can I split only a range of pages?", answer: "This tool splits all pages. Each page becomes one PDF in the ZIP. If you need only pages 3–5, download the ZIP and keep only those files after extracting." },
    { question: "Is quality lost when splitting?", answer: "No. The tool copies each page as-is into a new PDF. Content and quality are preserved. No re-encoding or compression is applied." },
  ],
  "png-to-pdf": [
    { question: "How do I convert a PNG to PDF online?", answer: "Upload your PNG file. The tool embeds it in a single-page PDF in your browser using pdf-lib. Click the button to create the PDF, then download. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my images sent to a server?", answer: "No. The tool uses pdf-lib in your browser to build the PDF. Your PNG never leaves your device." },
    { question: "Why convert PNG to PDF?", answer: "A single PDF is easier to share or submit than an image file in many cases. Many forms and systems accept only PDF. Converting one PNG to a one-page PDF is useful for documents, forms, or when the recipient expects PDF." },
    { question: "What about transparency?", answer: "PNG can have transparency. When embedded in a PDF, transparent areas may appear as white or as defined in the PDF. For best results, the tool embeds the PNG as-is; complex transparency is preserved where the PDF format allows." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Upload your PNG, create the PDF, and download. No app install required." },
    { question: "Can I add multiple PNGs to one PDF?", answer: "This tool creates a one-page PDF from one PNG. For multiple images in one PDF, use the Images to PDF tool instead." },
    { question: "Is the PDF searchable?", answer: "No. The PDF contains your image as a single page. Text in the image is not selectable or searchable. For searchable PDFs you would need OCR or a tool that adds text layers." },
    { question: "What size will the PDF be?", answer: "The PDF size depends on the PNG. The image is embedded in the PDF, so the file is typically similar in size to or slightly larger than the original PNG." },
    { question: "Can I convert JPG to PDF?", answer: "This tool is for PNG to PDF only. For JPG or multiple images, use the Images to PDF tool." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very large PNGs may take longer and use more memory. For typical images (e.g. under 20 MB), the tool works well." },
  ],
  "jpg-to-pdf": [
    { question: "How do I convert JPG to PDF online?", answer: "Upload your JPG file. The tool embeds it in a single-page PDF in your browser using pdf-lib. Click the button to create the PDF, then download. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my images sent to a server?", answer: "No. The tool uses pdf-lib in your browser to build the PDF. Your JPG never leaves your device." },
    { question: "Why convert JPG to PDF?", answer: "A single PDF is easier to share or submit than an image file in many cases. Many forms and systems accept only PDF. Converting one JPG to a one-page PDF is useful for documents, forms, or when the recipient expects PDF." },
    { question: "Does it work with JPEG files?", answer: "Yes. The tool accepts both .jpg and .jpeg files. Both are the same format; the extension may vary." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Upload your JPG, create the PDF, and download. No app install required." },
    { question: "Can I add multiple JPGs to one PDF?", answer: "This tool creates a one-page PDF from one JPG. For multiple images in one PDF, use the Images to PDF tool instead." },
    { question: "Is the PDF searchable?", answer: "No. The PDF contains your image as a single page. Text in the image is not selectable or searchable. For searchable PDFs you would need OCR or a tool that adds text layers." },
    { question: "What size will the PDF be?", answer: "The PDF size depends on the JPG. The image is embedded in the PDF, so the file is typically similar in size to or slightly larger than the original JPG." },
    { question: "Can I convert PNG to PDF?", answer: "This tool is for JPG to PDF only. For PNG or multiple images, use the PNG to PDF or Images to PDF tool." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very large JPGs may take longer and use more memory. For typical images (e.g. under 20 MB), the tool works well." },
  ],
  "svg-to-png": [
    { question: "How do I convert SVG to PNG online?", answer: "Upload your SVG file. The tool loads it as an image in your browser, draws it onto a canvas at the SVG's natural size (or a default size), then exports the canvas as PNG. Click convert and download. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my files sent to a server?", answer: "No. Conversion runs entirely in your browser. The SVG is loaded via a local object URL and drawn on a canvas; your file never leaves your device." },
    { question: "Why convert SVG to PNG?", answer: "SVG is vector and scales well but is not supported everywhere (e.g. some social media or forms). PNG is a raster format that works in any app. Converting to PNG is useful when you need a fixed-size image or when the recipient only accepts PNG." },
    { question: "What resolution is the PNG?", answer: "The tool uses the SVG's natural width and height if available, or a fallback size (e.g. 1024×1024). The output PNG has that pixel dimensions. For higher resolution, use an SVG with larger intrinsic dimensions or a tool that lets you set output size." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Upload your SVG, convert, and download the PNG. No app install required." },
    { question: "Can I convert PNG to SVG?", answer: "This tool is for SVG to PNG only. Converting raster (PNG) to vector (SVG) requires tracing and is a different process; use a dedicated vectorizer or image-tracing tool." },
    { question: "Is transparency preserved?", answer: "SVG can have transparent areas. When drawn on a canvas and exported as PNG, transparency is preserved in the PNG. The canvas background is transparent by default." },
    { question: "Why did my SVG look different as PNG?", answer: "SVGs can use fonts, external resources, or complex effects that may not render identically in the browser's canvas. For best results use self-contained SVGs with embedded or system fonts." },
    { question: "What is the maximum size?", answer: "Limits depend on your device and browser canvas limits (often 16384px per side). Very large dimensions may fail or use a lot of memory. Typical SVGs (up to a few thousand pixels) work without issues." },
    { question: "Can I convert multiple SVGs?", answer: "This tool converts one file at a time. For batch conversion, use the tool repeatedly." },
  ],
  "rotate-pdf": [
    { question: "How do I rotate a PDF online?", answer: "Upload your PDF file. Choose a rotation angle (90°, 180°, or 270°) using the buttons. Click the rotate button. The tool applies the rotation to every page in your browser using pdf-lib, then you download the result. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my PDFs sent to a server?", answer: "No. Rotation is done in your browser using pdf-lib. Your PDF never leaves your device." },
    { question: "Can I rotate only some pages?", answer: "This tool rotates all pages by the same angle. If you need to rotate only certain pages, use a PDF editor that supports per-page rotation, or split the PDF, rotate the relevant parts, then merge." },
    { question: "What rotation angles are available?", answer: "You can rotate by 90° (clockwise), 180°, or 270° (equivalent to 90° counter-clockwise). These cover the typical needs for correcting orientation." },
    { question: "Does it work with password-protected PDFs?", answer: "Password-protected PDFs must be unlocked first. Open the PDF with the correct password in another app, save without password, then use that copy here." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Upload your PDF, choose the angle, rotate, and download. No app install required." },
    { question: "Is quality lost when rotating?", answer: "No. The tool sets the page rotation metadata in the PDF. Content and quality are preserved; no re-encoding or re-compression is applied." },
    { question: "Why is my PDF rotated the wrong way?", answer: "If the result is not what you expected, try the other angle (e.g. 270° instead of 90°). Rotation is applied clockwise: 90° turns the page once to the right." },
    { question: "Is there a page limit?", answer: "There is no fixed limit. Very long PDFs may take longer and use more memory. For typical documents (e.g. under 100 pages), rotation works well." },
    { question: "Can I rotate and merge in one go?", answer: "This tool only rotates. To rotate and then combine with other PDFs, rotate first, download, then use the Merge PDF tool with the rotated file and others." },
  ],
  "image-to-webp": [
    { question: "How do I convert an image to WebP online?", answer: "Upload your image (JPG, PNG or WebP). Set the quality with the slider (0–100; 80 is a good default). Click “Convert to WebP” and download the result. Everything runs in your browser; no data is sent to any server." },
    { question: "Why use WebP?", answer: "WebP often produces smaller file sizes than JPG or PNG at similar visual quality, which speeds up web pages. All modern browsers support WebP. Converting to WebP is useful for websites, apps, and when you want to save space without losing much quality." },
    { question: "Are my images sent to a server?", answer: "No. Conversion runs entirely in your browser using the Canvas API. Your file never leaves your device." },
    { question: "What does the quality slider do?", answer: "Lower values (e.g. 60) give smaller files but more compression; higher values (e.g. 90) keep more detail but larger files. We recommend 75–85 for a good balance. You can compare file size after conversion." },
    { question: "What formats can I upload?", answer: "You can upload JPG (JPEG), PNG, and WebP. The output is always WebP. If you already have WebP, you can re-encode it at a different quality." },
    { question: "Does it work on mobile?", answer: "Yes. Open the tool in your mobile browser, upload an image, set quality, convert, and download. No app install required." },
    { question: "Is transparency preserved?", answer: "WebP supports transparency. If your source is PNG or WebP with transparency, the output WebP can keep it. JPG has no transparency, so the result will be opaque." },
    { question: "Can I convert multiple images?", answer: "This tool converts one file at a time. For batch conversion, use the tool repeatedly or combine with other image tools." },
    { question: "What is the maximum image size?", answer: "Limits depend on your device and browser memory. Typical photos (several MB) work without issues. Very large images may take longer." },
    { question: "WebP vs JPG for photos?", answer: "WebP often gives 25–35% smaller files than JPG at similar quality. Use WebP when your platform supports it (websites, modern apps). Use JPG when you need maximum compatibility (e.g. some email clients or older systems)." },
  ],
  "pdf-to-png": [
    { question: "How do I convert PDF to PNG online?", answer: "Upload your PDF file. The tool renders each page to an image in the browser using PDF.js and the canvas, then encodes each as PNG. You can download each page as a separate PNG or all as a ZIP. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my PDFs sent to a server?", answer: "No. The PDF is loaded and rendered entirely in your browser. Your file never leaves your device." },
    { question: "What resolution are the PNGs?", answer: "The tool renders each page at a standard scale (e.g. 2x for clarity). You get a PNG per page suitable for web, email, or editing. For very high resolution you may need a desktop app." },
    { question: "Why PNG instead of JPG?", answer: "PNG is lossless and supports transparency. Use PDF to PNG when you need exact pixel reproduction, transparency, or when you will edit the images. Use PDF to JPG when you want smaller files and do not need transparency." },
    { question: "Can I choose which pages to convert?", answer: "This tool converts all pages. Each page becomes one PNG. You can delete unwanted PNGs after download or use a PDF tool to extract specific pages first." },
    { question: "Does it work with password-protected PDFs?", answer: "Password-protected PDFs must be unlocked first. Open the PDF with the correct password in another app, save without password, then use that copy here." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Large PDFs may take longer on mobile due to memory." },
    { question: "What about multi-page PDFs?", answer: "Each page is converted to a separate PNG. You get multiple files or one ZIP containing all pages in order." },
    { question: "Is there a page limit?", answer: "There is no fixed limit. Very long PDFs may take longer and use more memory. For typical documents (e.g. under 50 pages), conversion works well." },
    { question: "Is text still selectable in the PNG?", answer: "No. The output is an image (PNG). Text is not selectable or searchable. For editable text, use a PDF-to-text tool." },
  ],
  "gif-to-mp4": [
    { question: "How do I convert a GIF to MP4 online?", answer: "Upload your GIF file. The tool uses FFmpeg.wasm in your browser to convert it to MP4. Click “Convert to MP4”; a progress bar shows while processing. When done, download the MP4. Everything runs in your browser; no data is sent to any server." },
    { question: "Why convert GIF to MP4?", answer: "MP4 (H.264) is much smaller than GIF for the same visual quality and is supported everywhere. Converting GIF to MP4 reduces file size and improves playback on websites and social media. Many platforms prefer video (MP4) over GIF." },
    { question: "Are my files sent to a server?", answer: "No. Conversion runs entirely in your browser using FFmpeg.wasm. Your GIF never leaves your device." },
    { question: "Why does FFmpeg take a few seconds to load?", answer: "FFmpeg.wasm is a large WebAssembly module. It is downloaded once (from a CDN) and then cached by the browser. The first time you use the tool or after clearing cache, you will see a loading state for a few seconds." },
    { question: "Does it work on mobile?", answer: "Yes, in browsers that support WebAssembly and the required APIs. Some older mobile browsers may be slower or have limits. Try it in the latest Chrome or Safari." },
    { question: "What is the output quality?", answer: "The tool uses settings that keep good visual quality while ensuring compatibility (e.g. yuv420p, faststart). The MP4 is typically much smaller than the original GIF with similar or better appearance." },
    { question: "Can I convert MP4 to GIF?", answer: "This tool is for GIF to MP4 only. For video to GIF you would need a different tool that creates animated GIFs from video." },
    { question: "Is there a file size limit?", answer: "Practical limits depend on your device memory. Very large GIFs may take longer or cause the browser to slow down. Typical GIFs (a few MB) work without issues." },
    { question: "Why use MP4 instead of GIF on a website?", answer: "MP4 loads faster, uses less bandwidth, and often looks better than GIF. Modern HTML5 video supports MP4; you can autoplay, mute, and loop it like a GIF. Many sites (e.g. Twitter, Discord) show MP4s as inline video." },
    { question: "Does it work in all browsers?", answer: "FFmpeg.wasm requires a modern browser with WebAssembly support. Chrome, Firefox, Safari, and Edge (recent versions) work. Some corporate or very old browsers may not support it." },
  ],
  "crop-image": [
    { question: "How do I crop an image online?", answer: "Upload your image (JPG, PNG or WebP). The preview shows with a selection overlay. Drag the edges or corners of the selection to define the crop area. The dimensions update in real time. Click \"Crop Image\" to apply and download the result as PNG. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my images sent to a server?", answer: "No. Cropping is done entirely in your browser using the Canvas API. Your image never leaves your device." },
    { question: "What format is the output?", answer: "The cropped result is always downloaded as PNG. PNG is lossless and supports transparency if your source has it." },
    { question: "Can I crop to exact dimensions?", answer: "You define the crop area visually by dragging. The tool shows the size in pixels (e.g. 320 × 240 px) so you can adjust until you get the dimensions you need." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Touch the edges of the selection to resize the crop area, then tap the crop button and download. No app install required." },
    { question: "Why would I crop an image?", answer: "Common reasons: remove unwanted edges, focus on a subject, fit an image to a specific aspect ratio or size (e.g. profile picture, banner), or prepare graphics for social media or thumbnails." },
    { question: "Is the original image modified?", answer: "No. The original file is never changed. You download a new PNG with only the cropped area. Keep your original if you need it." },
    { question: "What image formats can I upload?", answer: "You can upload JPG (JPEG), PNG, and WebP. These are the most common image formats. The output is always PNG." },
    { question: "Can I crop multiple images?", answer: "This tool crops one image at a time. For batch cropping, use it repeatedly or combine with other image tools." },
    { question: "What is the maximum image size?", answer: "Limits depend on your device and browser memory. Typical photos (several MB) work without issues. Very large images may take longer to load and display." },
  ],
  "bmp-to-jpg": [
    { question: "How do I convert BMP to JPG online?", answer: "Upload your BMP file. Click \"Convert to JPG\" and the tool draws the image on a canvas in your browser and exports it as JPG. Download the result. Everything runs in your browser; no data is sent to any server." },
    { question: "Why convert BMP to JPG?", answer: "BMP files are often large and not ideal for web or email. JPG is widely supported and produces much smaller file sizes with good quality. Converting to JPG is useful for sharing, uploading to websites, or when the recipient expects JPG." },
    { question: "Are my images sent to a server?", answer: "No. Conversion runs entirely in your browser using the Canvas API. Your BMP never leaves your device." },
    { question: "Is quality lost?", answer: "JPG uses lossy compression. The tool uses a quality setting (e.g. 92%) that keeps visual quality high while reducing file size. For most uses the result looks very good." },
    { question: "What about transparency in BMP?", answer: "BMP can have transparency in some variants. JPG does not support transparency. The tool draws the image on a white background, so any transparent areas become white in the JPG." },
    { question: "Does it work on mobile?", answer: "Yes. Open the tool in your mobile browser, upload a BMP, convert, and download the JPG. No app install required." },
    { question: "Can I convert JPG to BMP?", answer: "This tool is for BMP to JPG only. For JPG to BMP or other conversions, use a different tool." },
    { question: "What is the maximum file size?", answer: "There is no fixed limit. Very large BMPs may take longer to load and convert. Typical files (a few MB) work without issues." },
    { question: "Why is my BMP not loading?", answer: "The tool accepts standard BMP format (image/bmp). If your file does not load, ensure it is a valid BMP. Some very old or uncommon BMP variants might not be supported by the browser." },
    { question: "What resolution is the JPG?", answer: "The output JPG has the same pixel dimensions (width and height) as the original BMP. Only the format and compression change; resolution is preserved." },
  ],
  "extract-pdf-pages": [
    { question: "How do I extract pages from a PDF online?", answer: "Upload your PDF file. The tool shows the total number of pages. Enter the page range you want (e.g. 1-3, 5, 7-9) in the text field. Click \"Extract pages\" to create a new PDF containing only those pages, then download. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my PDFs sent to a server?", answer: "No. Extraction is done in your browser using pdf-lib. Your PDF never leaves your device." },
    { question: "What format is the page range?", answer: "You can enter single pages (e.g. 5), ranges (e.g. 1-3 for pages 1, 2, 3), or a combination separated by commas (e.g. 1-3, 5, 7-9). Pages are 1-based (first page is 1)." },
    { question: "What if I enter an invalid range?", answer: "The tool validates the input. If a page number is out of bounds (e.g. page 20 when the PDF has 10 pages) or the format is invalid, an error message is shown. Correct the range and try again." },
    { question: "Does it work with password-protected PDFs?", answer: "Password-protected PDFs must be unlocked first. Open the PDF with the correct password in another app, save without password, then use that copy here." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Upload your PDF, enter the page range, extract, and download. No app install required." },
    { question: "Is the order of pages preserved?", answer: "Yes. The extracted PDF contains the selected pages in the order you specified (e.g. 1-3, 5, 7-9 gives pages 1, 2, 3, 5, 7, 8, 9 in that order)." },
    { question: "Can I extract all pages?", answer: "Yes. Enter a range that covers all pages (e.g. 1-10 for a 10-page PDF). The result is a copy of the original. For splitting each page into a separate file, use the Split PDF tool." },
    { question: "Is there a page limit?", answer: "There is no fixed limit. Very long PDFs may take longer and use more memory. For typical documents (e.g. under 100 pages), extraction works well." },
    { question: "What is the difference between extract and split?", answer: "Extract creates one PDF containing only the pages you choose (e.g. pages 2, 5, 7). Split creates one PDF per page and packs them in a ZIP. Use extract when you want a single PDF with selected pages; use split when you want every page as a separate file." },
  ],
  "tiff-to-jpg": [
    { question: "How do I convert TIFF to JPG online?", answer: "Upload your TIFF file. Click \"Convert to JPG\". The tool uses the browser canvas to draw the image on a white background and export as JPG at 92% quality. Download the result. Everything runs in your browser; no data is sent to any server. Note: TIFF is supported natively in Chrome and Safari; if your browser does not support it, try Chrome or Safari." },
    { question: "Why convert TIFF to JPG?", answer: "TIFF is often used for high-quality images and scans but produces large files. JPG is widely supported and much smaller, making it better for web, email, or when the recipient expects JPG. Converting TIFF to JPG reduces file size while keeping good visual quality." },
    { question: "Are my images sent to a server?", answer: "No. Conversion runs entirely in your browser using the Canvas API. Your TIFF never leaves your device." },
    { question: "My TIFF does not load. What should I do?", answer: "Modern Chrome and Safari support TIFF natively. If your browser does not support TIFF (e.g. some Firefox versions), the tool will show a message suggesting you try Chrome or Safari. You can also try opening the TIFF in an image editor and exporting as JPG, then use that file elsewhere if needed." },
    { question: "Is quality lost?", answer: "JPG uses lossy compression. The tool uses 92% quality to keep visual quality high while reducing file size. For most uses the result looks very good. TIFF is often lossless; the JPG will be slightly lossy by nature." },
    { question: "Does it work on mobile?", answer: "Yes, in Chrome or Safari on mobile, which support TIFF. Open the tool, upload your TIFF, convert, and download the JPG. No app install required." },
    { question: "Can I convert JPG to TIFF?", answer: "This tool is for TIFF to JPG only. For other conversions use the appropriate tool (e.g. image to PDF, or an editor that exports TIFF)." },
    { question: "What about multi-page TIFF?", answer: "This tool processes one image at a time. If your TIFF has multiple pages (e.g. a scan of several sheets), only the first frame may be used. For multi-page documents consider splitting or converting each page separately." },
    { question: "What is the maximum file size?", answer: "There is no fixed limit. Very large TIFFs may take longer to load and convert. Typical files (several MB) work without issues. Limits depend on your device and browser memory." },
    { question: "Why use JPG instead of TIFF for web?", answer: "JPG is universally supported by browsers and produces much smaller files. TIFF is better for archiving or print workflows. For web, email, or sharing, JPG is the practical choice." },
  ],
  "add-watermark-pdf": [
    { question: "How do I add a watermark to a PDF online?", answer: "Upload your PDF file. Enter the watermark text (e.g. CONFIDENTIAL), set the opacity with the slider, and choose the position (center, diagonal, or bottom corner). Click \"Add watermark\". The tool adds the text to every page using pdf-lib in your browser, then you download the result. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my PDFs sent to a server?", answer: "No. Watermarking is done in your browser using pdf-lib. Your PDF never leaves your device." },
    { question: "Can I change the watermark text?", answer: "Yes. Before clicking Add watermark, type any text in the watermark field. The default is \"CONFIDENTIAL\". You can use any short phrase or word." },
    { question: "What does the opacity slider do?", answer: "The slider controls how light or dark the watermark appears. Lower values make the text more subtle (lighter gray); higher values make it more visible. The tool uses gray color; the slider adjusts the intensity so the watermark does not overwhelm the content." },
    { question: "What position options are there?", answer: "You can place the watermark in the center of each page, diagonally across the page (rotated 45°), or in the bottom corner. Choose the option that best fits your document layout." },
    { question: "Does it work with password-protected PDFs?", answer: "Password-protected PDFs must be unlocked first. Open the PDF with the correct password in another app, save without password, then use that copy here." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Upload your PDF, set the watermark options, add the watermark, and download. No app install required." },
    { question: "Is there a page limit?", answer: "There is no fixed limit. Very long PDFs may take longer and use more memory. For typical documents (e.g. under 100 pages), watermarking works well." },
    { question: "Can I remove a watermark later?", answer: "This tool only adds watermarks. It does not remove existing watermarks. If you need to remove a watermark, you would need a PDF editor that supports editing or removing overlay content." },
    { question: "What font is used for the watermark?", answer: "The tool uses the standard Helvetica font (built into PDF). The text is drawn as vector text so it stays sharp at any zoom level." },
  ],
  "mp4-to-gif": [
    { question: "How do I convert MP4 to GIF online?", answer: "Upload your MP4 file. The tool uses FFmpeg.wasm in your browser to convert it to GIF. Click \"Convert to GIF\"; a progress bar shows while processing. When done, download the GIF. Everything runs in your browser; no data is sent to any server. Note: GIF files are typically larger than MP4; for web use, consider keeping MP4 when possible." },
    { question: "Why convert MP4 to GIF?", answer: "GIF is supported everywhere and can be embedded in older systems, emails, or platforms that do not support video. Converting MP4 to GIF is useful when you need a single file that plays automatically without a video player. Note: GIF is usually larger than MP4; use when GIF is required." },
    { question: "Are my files sent to a server?", answer: "No. Conversion runs entirely in your browser using FFmpeg.wasm. Your MP4 never leaves your device." },
    { question: "Why does FFmpeg take a few seconds to load?", answer: "FFmpeg.wasm is a large WebAssembly module. It is downloaded once (from a CDN) and then cached by the browser. The first time you use the tool or after clearing cache, you will see a loading state for a few seconds." },
    { question: "Why is the GIF so large?", answer: "GIF is a legacy format and is less efficient than video (MP4). The tool uses fps=10 and scale=480 to keep the GIF at a reasonable size, but it will often be larger than the original MP4. For web use, consider keeping MP4 when the platform supports it." },
    { question: "Does it work on mobile?", answer: "Yes, in browsers that support WebAssembly. Chrome and Safari on mobile work. Conversion may take longer on slower devices." },
    { question: "Can I convert GIF to MP4?", answer: "This tool is for MP4 to GIF only. Use the GIF to MP4 tool for the reverse conversion (GIF to MP4 produces smaller files)." },
    { question: "What is the output size and quality?", answer: "The tool uses 10 fps and a maximum width of 480 px to keep the GIF at a reasonable file size. Quality is good for short clips; for long videos the GIF can become very large." },
    { question: "Is there a file size limit?", answer: "Practical limits depend on your device memory. Very long or high-resolution MP4s may take a long time and produce very large GIFs. Short clips (e.g. under 30 seconds) work best." },
    { question: "Does it work in all browsers?", answer: "FFmpeg.wasm requires a modern browser with WebAssembly support. Chrome, Firefox, Safari, and Edge (recent versions) work. Some corporate or very old browsers may not support it." },
  ],
  "jpg-to-webp": [
    { question: "How do I convert JPG to WebP online?", answer: "Upload your JPG file. Set the quality with the slider (0–100; 80 is a good default). Click \"Convert to WebP\" and download the result. Everything runs in your browser using the Canvas API; no data is sent to any server." },
    { question: "Why convert JPG to WebP?", answer: "WebP often produces smaller file sizes than JPG at similar visual quality, which speeds up web pages and saves bandwidth. All modern browsers support WebP. Converting JPG to WebP is useful for websites and when you want smaller files without losing much quality." },
    { question: "Are my images sent to a server?", answer: "No. Conversion runs entirely in your browser using the Canvas API. Your JPG never leaves your device." },
    { question: "What does the quality slider do?", answer: "Lower values (e.g. 60) give smaller files but more compression; higher values (e.g. 90) keep more detail but larger files. We recommend 75–85 for a good balance. Default is 80." },
    { question: "Does it work on mobile?", answer: "Yes. Open the tool in your mobile browser, upload a JPG, set quality, convert, and download. No app install required." },
    { question: "Can I convert WebP to JPG?", answer: "This tool is for JPG to WebP only. Use the WebP to JPG tool for the reverse conversion." },
    { question: "Is transparency supported?", answer: "JPG does not support transparency. The output WebP will be opaque. For transparent WebP, start from a PNG or image that has transparency." },
    { question: "What is the maximum image size?", answer: "Limits depend on your device and browser memory. Typical photos (several MB) work without issues." },
    { question: "Why use WebP instead of JPG for web?", answer: "WebP often gives 25–35% smaller files than JPG at similar quality. Use WebP when your platform supports it (websites, modern apps). Use JPG when you need maximum compatibility." },
    { question: "Can I convert multiple JPGs?", answer: "This tool converts one file at a time. For batch conversion, use the tool repeatedly." },
  ],
  "pdf-to-text": [
    { question: "How do I extract text from a PDF online?", answer: "Upload your PDF file. Click \"Extract text\". The tool uses PDF.js in your browser to get the text from each page. The result is shown in a text area; you can copy it or download as a .txt file. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my PDFs sent to a server?", answer: "No. Text extraction is done in your browser using PDF.js. Your PDF never leaves your device." },
    { question: "Why is the extracted text empty?", answer: "If the PDF contains only images (e.g. a scanned document), there is no selectable text. The tool extracts only text that is embedded in the PDF. For scanned PDFs you would need OCR (optical character recognition) to get text from images." },
    { question: "What format is the output?", answer: "You see the text in a text area on the page. You can copy it to the clipboard or download it as a plain .txt file. Pages are separated with a \"--- Page N ---\" marker." },
    { question: "Does it work with password-protected PDFs?", answer: "Password-protected PDFs must be unlocked first. Open the PDF with the correct password in another app, save without password, then use that copy here." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Upload your PDF, extract text, then copy or download. No app install required." },
    { question: "Is the order of text preserved?", answer: "Yes. Text is extracted page by page in order. Each page's text is concatenated with a separator so you can see where pages change." },
    { question: "Can I extract text from images in the PDF?", answer: "No. This tool extracts only embedded text (actual text layer). Text that appears only inside images (e.g. in a scan) is not extracted. For that you need an OCR tool." },
    { question: "Is there a page limit?", answer: "There is no fixed limit. Very long PDFs may take longer and use more memory. For typical documents (e.g. under 100 pages), extraction works well." },
    { question: "What is the difference between PDF to text and PDF to JPG?", answer: "PDF to text extracts the text content so you can copy, search, or edit it. PDF to JPG converts each page into an image. Use PDF to text when you need the words; use PDF to JPG when you need images of the pages." },
  ],
  "create-zip": [
    { question: "How do I create a ZIP file online?", answer: "Upload one or more files using the drop zone or file picker. You can add more files; each appears in the list. Remove any you do not want, then click \"Create ZIP\". The tool uses JSZip in your browser to build the archive. Download result.zip. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my files sent to a server?", answer: "No. The ZIP is created in your browser using JSZip. Your files never leave your device." },
    { question: "What file types can I add?", answer: "You can add any file type: documents, images, videos, etc. All files are added to the ZIP with their original names. There is no restriction on file type." },
    { question: "Can I remove files from the list before creating the ZIP?", answer: "Yes. Each file in the list has a remove button. Click it to remove that file from the list. Then click \"Create ZIP\" to build the archive with the remaining files." },
    { question: "What is the name of the downloaded file?", answer: "The downloaded file is named result.zip. You can rename it after downloading if you prefer." },
    { question: "Does it work on mobile?", answer: "Yes. The tool runs in the mobile browser. Add files from your device, create the ZIP, and download. No app install required." },
    { question: "Is there a limit on how many files I can add?", answer: "There is no fixed limit. Very many or very large files may use a lot of memory and take longer. For typical use (e.g. dozens of files, a few hundred MB total), the tool works well." },
    { question: "Can I create a ZIP with folders?", answer: "This tool adds all files to the root of the ZIP (no folder structure). For a ZIP with folders, you would need to use a desktop app or a tool that supports folder structure." },
    { question: "Why use a browser ZIP tool?", answer: "Creating a ZIP in the browser is quick, private (files never leave your device), and requires no software install. Use it when you need to bundle files for email, upload, or backup." },
    { question: "Can I add more files after I started?", answer: "Yes. Keep adding files via the drop zone or file input. The list updates. When you are ready, click \"Create ZIP\". You can also remove individual files from the list before creating." },
  ],
  "trim-video": [
    { question: "How do I trim a video online?", answer: "Upload your video (MP4, WebM, or MOV). The tool shows the total duration. Enter the start time (seconds) and end time (seconds) for the segment you want to keep. Click \"Trim video\". FFmpeg.wasm cuts the segment in your browser using stream copy (no re-encoding), so it is fast. Download the result. Your file never leaves your device." },
    { question: "Are my videos sent to a server?", answer: "No. Trimming runs entirely in your browser using FFmpeg.wasm. Your video never leaves your device." },
    { question: "What formats are supported?", answer: "You can upload MP4, WebM, and MOV. The output keeps the same format as the input. Trimming uses \"copy\" mode, so no re-encoding and no quality loss." },
    { question: "Why does FFmpeg take a few seconds to load?", answer: "FFmpeg.wasm is a large WebAssembly module. It is downloaded once and cached. The first time you use the tool (or after clearing cache), you will see a short loading state." },
    { question: "Can I set start and end in minutes?", answer: "The inputs are in seconds. For example, 1:30 is 90 seconds—enter 90 as the end time. You can use whole numbers only; for frame-accurate cuts, use a desktop editor." },
    { question: "Does it work on mobile?", answer: "Yes, in browsers that support WebAssembly (Chrome, Safari). Trimming with copy mode is fast and works well on mobile." },
    { question: "Is there a maximum video length?", answer: "There is no fixed limit. Very long videos may take longer to load and process. Practical limits depend on your device memory." },
    { question: "Why is the output not exactly at the times I set?", answer: "With \"-c copy\", cuts happen at the nearest keyframe. For frame-accurate trimming you would need to re-encode (slower). This tool prioritizes speed and no quality loss." },
    { question: "Can I trim multiple segments?", answer: "This tool produces one continuous segment (start to end). For multiple segments or complex editing, use a desktop video editor." },
    { question: "Does it work in all browsers?", answer: "FFmpeg.wasm requires a modern browser with WebAssembly. Chrome, Firefox, Safari, and Edge (recent versions) work." },
  ],
  "video-to-mp3": [
    { question: "How do I extract MP3 from a video online?", answer: "Upload your video (MP4, WebM, MOV, AVI, or MKV). Click \"Extract MP3\". The tool uses FFmpeg.wasm in your browser to strip the video and encode the audio as high-quality MP3. When done, download the .mp3 file. Everything runs in your browser; no data is sent to any server." },
    { question: "Are my files sent to a server?", answer: "No. Extraction runs entirely in your browser using FFmpeg.wasm. Your video never leaves your device." },
    { question: "What if the video has no audio?", answer: "If the video has no audio track, the tool will show an error. Only videos with an audio stream can be converted to MP3." },
    { question: "What quality is the MP3?", answer: "The tool uses -q:a 2, which is high-quality VBR MP3 (roughly 190 kbps average). Good for music and speech." },
    { question: "What video formats are supported?", answer: "MP4, WebM, MOV, AVI, and MKV. The tool reads the audio track and encodes it to MP3." },
    { question: "Why does FFmpeg take a few seconds to load?", answer: "FFmpeg.wasm is a large WebAssembly module. It is downloaded once and cached. The first time you use the tool you will see a short loading state." },
    { question: "Does it work on mobile?", answer: "Yes, in browsers that support WebAssembly. Chrome and Safari on mobile work. Longer videos may take more time on slower devices." },
    { question: "Can I extract audio from a streaming video?", answer: "You need to upload a video file from your device. The tool does not accept URLs or streaming sources." },
    { question: "Is there a length limit?", answer: "There is no fixed limit. Very long videos may take longer and use more memory. Practical limits depend on your device." },
    { question: "Does it work in all browsers?", answer: "FFmpeg.wasm requires a modern browser with WebAssembly. Chrome, Firefox, Safari, and Edge (recent versions) work." },
  ],
  "compress-video": [
    { question: "How do I compress a video online?", answer: "Upload your MP4 video. Choose a compression level: Light (good quality, ~40% smaller), Medium (balanced), or Strong (smaller file, lower quality). Click \"Compress video\". FFmpeg.wasm re-encodes the video in your browser. When done, you see the original and new size and can download. Processing can take several minutes for long videos." },
    { question: "Are my videos sent to a server?", answer: "No. Compression runs entirely in your browser using FFmpeg.wasm. Your video never leaves your device." },
    { question: "What do the compression levels mean?", answer: "Light uses CRF 28 (good quality, about 40% size reduction). Medium uses CRF 33 (noticeable but acceptable quality, about 60% smaller). Strong uses CRF 38 (smaller file, lower quality, about 75% smaller). Choose based on how much you need to reduce size." },
    { question: "Why does compression take so long?", answer: "Re-encoding video is CPU-intensive. FFmpeg.wasm runs in the browser, so speed depends on your device. Long or high-resolution videos can take several minutes. A progress bar shows the status." },
    { question: "What format is the output?", answer: "The output is MP4 (H.264 video, AAC audio), the same as typical for web and sharing." },
    { question: "Does it work on mobile?", answer: "Yes, but compression is CPU-intensive. On phones it may take longer; short clips work best." },
    { question: "Can I compress WebM or other formats?", answer: "This tool accepts MP4 input and produces MP4 output. For other formats, use a converter first or a desktop app." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very large videos may use a lot of memory and take a long time. Practical limits depend on your device." },
    { question: "Why use browser compression?", answer: "No upload to a server—your video stays on your device. Useful for quick size reduction when you cannot install software. For heavy or batch compression, a desktop app may be faster." },
    { question: "Does it work in all browsers?", answer: "FFmpeg.wasm requires a modern browser with WebAssembly. Chrome, Firefox, Safari, and Edge (recent versions) work." },
  ],
  "mute-video": [
    { question: "How do I mute a video online?", answer: "Upload your video (MP4, WebM, or MOV). Click \"Remove audio\". The tool uses FFmpeg.wasm in your browser to strip the audio track while copying the video stream without re-encoding, so it is very fast. Download the result. Your file never leaves your device." },
    { question: "Are my videos sent to a server?", answer: "No. Processing runs entirely in your browser using FFmpeg.wasm. Your video never leaves your device." },
    { question: "What formats are supported?", answer: "You can upload MP4, WebM, and MOV. The output keeps the same format as the input. The video stream is copied (no re-encoding), so quality is unchanged and processing is very fast." },
    { question: "Why does FFmpeg take a few seconds to load?", answer: "FFmpeg.wasm is a large WebAssembly module. It is downloaded once and cached. The first time you use the tool (or after clearing cache), you will see a short loading state." },
    { question: "Does it work on mobile?", answer: "Yes, in browsers that support WebAssembly (Chrome, Safari). Muting uses stream copy, so it is fast and works well on mobile." },
    { question: "What if the video has no audio?", answer: "If the video has no audio track, the tool will still produce a valid output (video only). The result is the same as the input without an audio stream." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very long videos may take longer to process. Practical limits depend on your device memory. Because we only copy the video stream and drop audio, processing is quick." },
    { question: "Why mute a video?", answer: "Common reasons: create a silent clip for social media, remove background noise or music you do not have rights to, prepare a video for adding your own voiceover later, or reduce file size by removing the audio track." },
    { question: "Can I get the audio back after muting?", answer: "No. This tool removes the audio permanently from the copy you download. Keep your original file if you might need the audio later." },
    { question: "Does it work in all browsers?", answer: "FFmpeg.wasm requires a modern browser with WebAssembly. Chrome, Firefox, Safari, and Edge (recent versions) work." },
  ],
  "video-speed": [
    { question: "How do I change video speed online?", answer: "Upload your video (MP4, WebM, or MOV). Choose a speed: 0.5x (slow motion), 0.75x (slightly slow), 1.5x (faster), or 2x (timelapse). Click \"Change speed\". FFmpeg.wasm re-encodes the video and audio at the chosen speed. When done, download the result. Your file never leaves your device." },
    { question: "Are my videos sent to a server?", answer: "No. Processing runs entirely in your browser using FFmpeg.wasm. Your video never leaves your device." },
    { question: "What do the speed options mean?", answer: "0.5x plays the video at half speed (slow motion). 0.75x is slightly slowed. 1.5x is 50% faster. 2x is double speed (timelapse). Both video and audio are adjusted so they stay in sync." },
    { question: "Why does it take a while to process?", answer: "Changing speed requires re-encoding the video and audio. FFmpeg.wasm runs in the browser, so speed depends on your device. A progress bar shows the status. Longer or higher-resolution videos take more time." },
    { question: "What format is the output?", answer: "The output is MP4 (H.264 video, AAC audio), which is widely supported. The original format (e.g. WebM, MOV) is converted to MP4 for the speed change." },
    { question: "Does it work on mobile?", answer: "Yes, in browsers that support WebAssembly. Re-encoding is CPU-intensive, so on phones it may take longer; short clips work best." },
    { question: "Can I use custom speed values?", answer: "This tool offers four fixed speeds (0.5x, 0.75x, 1.5x, 2x) that work reliably with audio sync. For other values you would need a desktop video editor." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very large or long videos may use a lot of memory and take a long time. Practical limits depend on your device." },
    { question: "Why change video speed?", answer: "Slow motion (0.5x, 0.75x) is useful for sports, tutorials, or dramatic effect. Faster speed (1.5x, 2x) is useful for timelapses, quick summaries, or fitting more content in less time." },
    { question: "Does it work in all browsers?", answer: "FFmpeg.wasm requires a modern browser with WebAssembly. Chrome, Firefox, Safari, and Edge (recent versions) work." },
  ],
  "add-audio-to-video": [
    { question: "How do I add or replace audio in a video online?", answer: "Upload a video (MP4, WebM, or MOV) in the video zone and an audio file (MP3, WAV, or AAC) in the audio zone. Click \"Replace audio\". The tool uses FFmpeg.wasm to replace the video's audio track with your file. If the audio is shorter than the video, the output is trimmed to the audio length; if the audio is longer, it is trimmed to the video length. Download the result. Your files never leave your device." },
    { question: "Are my files sent to a server?", answer: "No. Processing runs entirely in your browser using FFmpeg.wasm. Your video and audio never leave your device." },
    { question: "What if the audio is shorter than the video?", answer: "The output duration matches the shorter of the two: the video is trimmed to the length of the audio. So you get a video that ends when your audio ends." },
    { question: "What if the audio is longer than the video?", answer: "The output duration matches the video. The audio is trimmed to the video length, so only the part that fits is used." },
    { question: "What video and audio formats are supported?", answer: "Video: MP4, WebM, MOV. Audio: MP3, WAV, AAC. The output is always MP4 (H.264 video, AAC audio) for compatibility." },
    { question: "Why does FFmpeg take a few seconds to load?", answer: "FFmpeg.wasm is a large WebAssembly module. It is downloaded once and cached. The first time you use the tool you will see a short loading state." },
    { question: "Does it work on mobile?", answer: "Yes, in browsers that support WebAssembly. Upload the video and audio from your device, then replace and download. No app install required." },
    { question: "Can I keep the original video audio and add a second track?", answer: "No. This tool replaces the existing audio with your file. For multiple audio tracks or mixing, you would need a desktop video editor." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very long or high-resolution files may take longer and use more memory. Practical limits depend on your device." },
    { question: "Does it work in all browsers?", answer: "FFmpeg.wasm requires a modern browser with WebAssembly. Chrome, Firefox, Safari, and Edge (recent versions) work." },
  ],
  "resize-video": [
    { question: "How do I resize a video for social media online?", answer: "Upload your video (MP4, WebM, or MOV). Choose a format: 9:16 (TikTok/Reels), 1:1 (Instagram post), or 16:9 (YouTube). Click \"Resize video\". FFmpeg.wasm scales and pads the video in your browser; for vertical formats (9:16 and 1:1) it adds a blurred background instead of black bars. Download the result. Your file never leaves your device." },
    { question: "Are my videos sent to a server?", answer: "No. Resizing runs entirely in your browser using FFmpeg.wasm. Your video never leaves your device." },
    { question: "What do the format options mean?", answer: "9:16 (1080×1920) is vertical, ideal for TikTok, Reels, and Stories; the sides get a blurred fill. 1:1 (1080×1080) is square for Instagram posts; letterbox areas get blurred. 16:9 (1920×1080) is widescreen for YouTube; padding is black if the video is portrait." },
    { question: "Why does FFmpeg take a few seconds to load?", answer: "FFmpeg.wasm is a large WebAssembly module. It is downloaded once and cached. The first time you use the tool you will see a short loading state." },
    { question: "Does it work on mobile?", answer: "Yes, in browsers that support WebAssembly. Resizing may take a while on phones for long or high-resolution videos." },
    { question: "What format is the output?", answer: "The output is always MP4 (H.264 video, audio copied) for maximum compatibility with social platforms." },
    { question: "Will quality be reduced?", answer: "The video is scaled to fit the chosen size. If your video is smaller than the target, it is upscaled (can look soft). If it is larger, it is downscaled, which usually keeps good quality. The blurred areas are generated from the video, not re-encoded at full quality." },
    { question: "Can I use custom dimensions?", answer: "This tool offers three fixed social presets (9:16, 1:1, 16:9). For custom dimensions you would need a desktop video editor." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very long or high-resolution videos may take longer and use more memory. Practical limits depend on your device." },
    { question: "Does it work in all browsers?", answer: "FFmpeg.wasm requires a modern browser with WebAssembly. Chrome, Firefox, Safari, and Edge (recent versions) work." },
  ],
  "merge-videos": [
    { question: "How do I merge videos online?", answer: "Upload two or more MP4 videos using the drop zone or file picker. They appear in a list. Use the up/down buttons to reorder them. Remove any clip you do not want. Click \"Merge videos\". FFmpeg.wasm concatenates them in order in your browser. When done, download the single MP4. Your files never leave your device." },
    { question: "Are my videos sent to a server?", answer: "No. Merging runs entirely in your browser using FFmpeg.wasm. Your videos never leave your device." },
    { question: "Do all videos need the same resolution or codec?", answer: "The tool uses re-encoding (filter_complex concat) so different resolutions and codecs are supported. All clips are merged in sequence into one MP4. For best results, use similar resolution and frame rate." },
    { question: "Can a video have no audio?", answer: "The merge expects every input to have both video and audio. If one file has no audio track, the merge may fail. Use videos that all have an audio stream, or add a silent track with another tool first." },
    { question: "Why does FFmpeg take a few seconds to load?", answer: "FFmpeg.wasm is a large WebAssembly module. It is downloaded once and cached. The first time you use the tool you will see a short loading state." },
    { question: "Does it work on mobile?", answer: "Yes, in browsers that support WebAssembly. Merging several or long clips may take a while on phones." },
    { question: "Is there a limit on how many videos I can merge?", answer: "There is no fixed limit. Very many or very long videos may use a lot of memory and take a long time. For typical use (e.g. under 10 clips, a few minutes each), the tool works well." },
    { question: "What format is the output?", answer: "The output is a single MP4 (H.264 video, AAC audio) containing all clips in the order you set." },
    { question: "Can I change the order after uploading?", answer: "Yes. Use the up and down arrows next to each clip to reorder. The merged video will follow the order shown in the list." },
    { question: "Does it work in all browsers?", answer: "FFmpeg.wasm requires a modern browser with WebAssembly. Chrome, Firefox, Safari, and Edge (recent versions) work." },
  ],
  "loop-video": [
    { question: "How do I loop a video online?", answer: "Upload your video (MP4, WebM, or MOV). The tool shows the original duration. Choose how many times to repeat: 2x, 3x, 5x, or 10x. Click \"Create loop\". FFmpeg.wasm concatenates the video (and audio, if present) that many times in your browser. Download the result. Your file never leaves your device." },
    { question: "Are my videos sent to a server?", answer: "No. Looping runs entirely in your browser using FFmpeg.wasm. Your video never leaves your device." },
    { question: "What if the video has no audio?", answer: "The tool first tries to loop both video and audio. If the video has no audio track, it will loop only the video. The output is still a valid MP4." },
    { question: "Why does the output get so large?", answer: "Looping multiplies the duration: a 10-second video at 5x becomes 50 seconds and roughly 5× the file size. For long videos or high loop counts, the output can be very large. A warning is shown on the page." },
    { question: "Why does FFmpeg take a few seconds to load?", answer: "FFmpeg.wasm is a large WebAssembly module. It is downloaded once and cached. The first time you use the tool you will see a short loading state." },
    { question: "Does it work on mobile?", answer: "Yes, in browsers that support WebAssembly. Creating long loops (e.g. 10x) may take a while on phones." },
    { question: "Can I loop more than 10 times?", answer: "This tool offers 2x, 3x, 5x, and 10x. For more repeats you would need to run it again on the result or use a desktop editor." },
    { question: "What format is the output?", answer: "The output is MP4 (H.264 video, AAC audio if the source had audio) for compatibility." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very long or high-resolution videos looped many times can produce huge files and may run out of memory. Use shorter clips or fewer loops if you hit limits." },
    { question: "Does it work in all browsers?", answer: "FFmpeg.wasm requires a modern browser with WebAssembly. Chrome, Firefox, Safari, and Edge (recent versions) work." },
  ],
  "remove-background": [
    { question: "How do I remove the background from an image online?", answer: "Upload a JPG, PNG or WebP image. The first time you use the tool, the ML model (~50MB) will download and cache. Click the remove button; when processing finishes you see a before/after preview and can download a PNG with transparent background. Everything runs in your browser; no image is sent to a server." },
    { question: "Are my images sent to a server?", answer: "No. The @imgly/background-removal library runs entirely in your browser using WebAssembly. Your image never leaves your device. The model is downloaded from IMG.LY's CDN and cached locally." },
    { question: "Why does the first run take longer?", answer: "The neural network model (ONNX) and WASM files are about 50MB combined. They are downloaded once from the CDN and then cached by the browser. Subsequent runs are much faster." },
    { question: "What image formats are supported?", answer: "You can upload JPEG, PNG and WebP. The output is always PNG with transparency so you can place the subject on any background elsewhere." },
    { question: "Does it work on mobile?", answer: "Yes, in modern mobile browsers that support WebAssembly. The first load (model download) may take a while on slower connections; processing may also be slower on older phones." },
    { question: "Can I use the result commercially?", answer: "The library runs locally and produces a standard PNG. Usage rights depend on your source image and the @imgly/background-removal license; check the library terms for commercial use." },
    { question: "What if the result has rough edges?", answer: "The model does its best to segment the subject. Complex backgrounds or fine details (hair, fur) may show minor artifacts. For critical work, consider refining the result in an image editor." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit in the tool. Very large images use more memory and take longer to process. Practical limits depend on your device and browser." },
    { question: "Why PNG and not JPG?", answer: "PNG supports transparency (alpha channel), which is needed to show “no background”. JPG does not support transparency, so the output is always PNG." },
    { question: "Does it work in all browsers?", answer: "It requires a modern browser with WebAssembly support. Chrome, Firefox, Safari and Edge (recent versions) are supported. The library may use WebGPU if available for faster processing." },
  ],
  "resize-image-social": [
    { question: "How do I resize an image for social media?", answer: "Upload your image (JPG, PNG or WebP). Choose one of the six presets (e.g. IG Post 1080×1080, IG Story 1080×1920, Twitter 1200×675, YouTube Thumbnail 1280×720, Facebook Cover 820×312, LinkedIn Post 1200×627). Optionally pick a background color (default white). Click Resize. The image is scaled to fit inside the preset size with letterboxing; you can download the result as JPG." },
    { question: "Are my images sent to a server?", answer: "No. Resizing is done with the Canvas API in your browser. Your image never leaves your device." },
    { question: "What is the background color for?", answer: "When your image does not match the preset aspect ratio, the tool fills the remaining space (letterboxing) with a solid color. Default is white; you can change it with the color picker to match your brand or design." },
    { question: "Why is the output always JPG?", answer: "JPG at 92% quality is a good balance for social posts and keeps file size small. If you need PNG (e.g. for transparency), use the regular Resize Image tool or an image editor." },
    { question: "Does it work on mobile?", answer: "Yes. Open the tool in your mobile browser, upload an image, pick a preset and optional background color, then resize and download." },
    { question: "Can I use custom dimensions?", answer: "This tool only offers the six social presets. For custom dimensions use the main Resize Image tool on FileFlip." },
    { question: "Will quality be reduced?", answer: "The image is scaled to fit the preset. If your image is larger than the preset it is downscaled (quality is usually good). If it is smaller it is upscaled and may look softer." },
    { question: "What are the exact preset sizes?", answer: "IG Post 1080×1080; IG Story / TikTok 1080×1920; Twitter / X Post 1200×675; YouTube Thumbnail 1280×720; Facebook Cover 820×312; LinkedIn Post 1200×627. All in pixels." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very large images may take a few seconds to process depending on your device." },
    { question: "Does it work in all browsers?", answer: "Yes. Any modern browser that supports the Canvas API (Chrome, Firefox, Safari, Edge) can run this tool." },
  ],
  "add-text-to-image": [
    { question: "How do I add text to an image online?", answer: "Upload your image (JPG, PNG or WebP). Type your text (up to 200 characters). Adjust font size (12–120px), text color, and optionally enable a semi-transparent background behind the text. Choose position: Top Center, Center, or Bottom Center. The preview updates as you change options. Click the apply button to generate the image, then download. Output is JPG 92% or PNG if the original was PNG." },
    { question: "Are my images sent to a server?", answer: "No. Everything is drawn with the Canvas API in your browser. Your image never leaves your device." },
    { question: "Can I use a custom font?", answer: "This tool uses the browser's default sans-serif font (e.g. Arial or system UI) for simplicity and speed. For custom fonts you would need a desktop or advanced web editor." },
    { question: "What is the text background option?", answer: "When enabled, a semi-transparent dark rectangle is drawn behind the text to improve readability on busy or light backgrounds. When disabled, only a subtle shadow is used." },
    { question: "Does it work on mobile?", answer: "Yes. Upload an image, enter text, adjust size and color, pick position, then apply and download. The preview may be smaller on small screens." },
    { question: "Is there a character limit?", answer: "Yes, 200 characters. Longer text would require word wrap and more space; for long captions consider using an editor or splitting into multiple lines manually." },
    { question: "Why is the output JPG or PNG?", answer: "If your uploaded image was PNG, the result is PNG to preserve transparency if any. Otherwise the result is JPG at 92% quality for a good balance of size and quality." },
    { question: "Can I add multiple text blocks?", answer: "This tool adds a single text block with one position. For multiple text areas or more control use an image editor." },
    { question: "Is there a file size limit?", answer: "There is no fixed limit. Very large images may take a moment to process in the browser." },
    { question: "Does it work in all browsers?", answer: "Yes. Any modern browser that supports Canvas (Chrome, Firefox, Safari, Edge) can run this tool." },
  ],
};

export function getToolFaq(toolPath) {
  return toolFaqs[toolPath] || [];
}
